name: Build pakkit

on: push

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - run: sudo apt install wine64

    - run: curl -sf https://gobinaries.com/tj/node-prune | sh

    - run: npm install

    - run: npx electron-forge package --platform win32
    - run: cd out/pakkit-win32-x64/resources/app/; node-prune; npx electron-rebuild -v 8.5.2

    - run: npx electron-forge package --platform linux
    - run: cd out/pakkit-linux-x64/resources/app/; node-prune; npx electron-rebuild -v 8.5.2;
    - run: chmod +x out/pakkit-linux-x64/pakkit

    - run: npx electron-forge package --platform darwin
    - run: cd out/pakkit-darwin-x64/pakkit.app/Contents/Resources/app/; node-prune; npx electron-rebuild -v 8.5.2

    - run: mv out/pakkit-win32-x64 pakkit-windows-x64
    - run: mv out/pakkit-linux-x64 pakkit-linux-x64
    - run: mv out/pakkit-darwin-x64 pakkit-macos-x64

    - run: zip -r -y out/pakkit-windows-x64.zip pakkit-windows-x64/
    - run: zip -r -y out/pakkit-linux-x64.zip pakkit-linux-x64/
    - run: zip -r -y out/pakkit-macos-x64.zip pakkit-macos-x64/

    - uses: actions/upload-artifact@v1.0.0
      if: ${{ github.ref != 'refs/heads/master' }}
      with:
        name: pakkit-windows-x64
        path: pakkit-windows-x64/

    - uses: actions/upload-artifact@v1.0.0
      if: ${{ github.ref != 'refs/heads/master' }}
      with:
        name: pakkit-linux-x64
        path: pakkit-linux-x64/

    - uses: actions/upload-artifact@v1.0.0
      if: ${{ github.ref != 'refs/heads/master' }}
      with:
        name: pakkit-macos-x64
        path: pakkit-macos-x64/

    - id: create_release
      uses: actions/create-release@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: github-${{ github.run_number }}
        release_name: GitHub build ${{ github.run_number }}
        body: github-${{ github.run_number }}

    - uses: actions/upload-release-asset@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: out/pakkit-windows-x64.zip
        asset_name: pakkit-windows-x64.zip
        asset_content_type: application/zip

    - uses: actions/upload-release-asset@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: out/pakkit-linux-x64.zip
        asset_name: pakkit-linux-x64.zip
        asset_content_type: application/zip

    - uses: actions/upload-release-asset@v1
      if: ${{ github.ref == 'refs/heads/master' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: out/pakkit-macos-x64.zip
        asset_name: pakkit-macos-x64.zip
        asset_content_type: application/zip
